name: Build headless

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Download submodules
      run: |
        git submodule update --init --recursive

    - name: Install LLVM 16 from official APT repo
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17 all
        sudo apt-get install -y libclang-17-dev llvm-17-dev clang-tools-17

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_DIR=/usr/lib/llvm-17/lib/cmake/llvm \
          -DClang_DIR=/usr/lib/llvm-17/lib/cmake/clang \
          -DCMAKE_CXX_FLAGS=-lstdc++fs \
          -DCMAKE_C_COMPILER=clang-17 \
          -DCMAKE_CXX_COMPILER=clang++-17

    - name: Build
      run: cmake --build build --config Release

    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: headless-${{ runner.os }}
        path: build/headless
